const missions=[
{title:'Kepimpinan Kesukuan',qs:[
{q:'Apakah ciri yang paling tepat tentang kepimpinan kesukuan?',a:'Ketua mengurus kelompok masyarakat berdasarkan adat dan kepentingan suku',w:['Ketua mengurus semua lembah sungai tanpa mengira suku','Ketua dilantik untuk mengawal kegiatan perdagangan sahaja','Ketua hanya berperanan dalam upacara tanpa kuasa masyarakat']},
{q:'Pernyataan berikut berkaitan ketua masyarakat. I Menjaga keharmonian. II Menyelesaikan pertikaian. III Memelihara adat. IV Menghapuskan identiti suku. Pilih kombinasi yang tepat.',a:'I, II dan III',w:['I dan IV','II dan IV','III dan IV']},
{q:'Sebuah komuniti memilih seorang tokoh yang arif tentang adat untuk memimpin mereka. Apakah sistem yang paling berkaitan?',a:'Kepimpinan kesukuan',w:['Kepimpinan lembah sungai','Pentadbiran pelabuhan','Pemerintahan pusat']},
{q:'Mengapakah kewibawaan ketua penting dalam masyarakat kesukuan?',a:'Memastikan keputusan dan adat dihormati oleh anggota masyarakat',w:['Meluaskan kuasa ke semua kawasan sungai','Menggantikan kegiatan ekonomi tradisional','Menghapuskan peranan keluarga dalam komuniti']},
{q:'Antara berikut, pasangan manakah paling tepat?',a:'Ketua suku — menjaga kepentingan dan keharmonian kelompok',w:['Ketua suku — menguasai semua sungai di Borneo','Ketua suku — menentukan harga semua barang dagangan','Ketua suku — mengetuai pentadbiran kuasa luar']}]},
{title:'Kepimpinan Lembah Sungai',qs:[
{q:'Mengapakah lembah sungai boleh menjadi asas kawasan pengaruh seorang pemimpin?',a:'Petempatan dan kegiatan masyarakat tertumpu di sepanjang sungai',w:['Semua masyarakat diwajibkan tinggal di muara','Sungai hanya digunakan untuk upacara masyarakat','Kawasan pedalaman tidak mempunyai sebarang penduduk']},
{q:'I Laluan perhubungan. II Sumber kehidupan. III Kawasan petempatan. IV Memutuskan hubungan masyarakat. Apakah kombinasi kepentingan sungai yang tepat?',a:'I, II dan III',w:['I dan IV','II dan IV','III dan IV']},
{q:'Seorang pemimpin menguasai petempatan dari bahagian hulu hingga ke hilir sungai. Situasi ini menunjukkan...',a:'Kawasan pengaruh berkait rapat dengan lembah sungai',w:['Kawasan pengaruh ditentukan oleh jenis tanaman','Kuasa pemimpin terhad kepada kawasan pantai','Pentadbiran tidak berkaitan dengan petempatan']},
{q:'Apakah sebab paling munasabah sungai penting kepada pembentukan petempatan?',a:'Memudahkan pergerakan manusia serta membekalkan sumber kehidupan',w:['Memisahkan sepenuhnya hubungan antara komuniti','Menghalang pertukaran hasil antara kawasan','Menyebabkan masyarakat meninggalkan kegiatan ekonomi']},
{q:'Pasangan manakah menunjukkan hubungan yang tepat?',a:'Lembah sungai — petempatan, perhubungan dan kawasan pengaruh',w:['Lembah sungai — kawasan tanpa kegiatan ekonomi','Lembah sungai — pusat pentadbiran kuasa Barat sahaja','Lembah sungai — kawasan yang dielakkan masyarakat tempatan']}]},
{title:'Kegiatan Ekonomi',qs:[
{q:'Mengapakah kegiatan ekonomi masyarakat Sabah dan Sarawak berbeza mengikut kawasan?',a:'Masyarakat menyesuaikan kegiatan dengan bentuk muka bumi dan sumber setempat',w:['Setiap kawasan diwajibkan menghasilkan barang yang sama','Semua kegiatan ditentukan oleh pedagang dari luar','Masyarakat hanya bergantung pada satu jenis pekerjaan']},
{q:'I Menangkap ikan. II Mengutip hasil hutan. III Pertanian. IV Industri automobil. Pilih kegiatan yang sesuai dengan ekonomi tradisional.',a:'I, II dan III',w:['I dan IV','II dan IV','III dan IV']},
{q:'Sebuah komuniti tinggal berhampiran sungai yang kaya dengan sumber akuatik. Kegiatan yang paling sesuai ialah...',a:'Menangkap ikan sambil menggunakan sungai sebagai laluan perhubungan',w:['Mengusahakan tanaman tanah tinggi sebagai kegiatan utama','Mengusahakan perlombongan di semua kawasan sungai','Menjalankan perdagangan laut tanpa menggunakan sungai']},
{q:'Mengapakah hasil hutan penting kepada masyarakat tempatan?',a:'Boleh digunakan sendiri dan ditukar atau diperdagangkan',w:['Hanya digunakan sebagai hiasan rumah','Tidak mempunyai nilai dalam kehidupan masyarakat','Menggantikan sepenuhnya hasil pertanian dan perikanan']},
{q:'Antara pasangan berikut, yang manakah paling munasabah?',a:'Kawasan sungai — perikanan dan perhubungan',w:['Kawasan sungai — penternakan unta','Kawasan hutan — perusahaan kapal wap','Kawasan pedalaman — perdagangan laut utama']}]},
{title:'Keunikan Masyarakat',qs:[
{q:'Apakah faktor yang paling jelas mencerminkan keunikan masyarakat Sabah dan Sarawak?',a:'Kepelbagaian etnik, bahasa, adat dan cara hidup',w:['Keseragaman bahasa dan adat semua masyarakat','Penghapusan identiti setiap kelompok masyarakat','Penggunaan satu bentuk budaya bagi semua kawasan']},
{q:'I Adat. II Bahasa. III Cara hidup. IV Identiti yang seragam. Pilih unsur yang menunjukkan kepelbagaian masyarakat.',a:'I, II dan III',w:['I dan IV','II dan IV','III dan IV']},
{q:'Dua komuniti tinggal di kawasan berbeza lalu mempunyai adat dan kegiatan harian yang berlainan. Apakah kesimpulan terbaik?',a:'Persekitaran dan warisan komuniti membentuk kepelbagaian cara hidup',w:['Semua masyarakat sepatutnya mempunyai adat yang sama','Perbezaan cara hidup membuktikan masyarakat tidak berhubung','Adat hanya terbentuk akibat kegiatan perdagangan luar']},
{q:'Mengapakah adat perlu dipelihara?',a:'Menjadi panduan kehidupan serta sebahagian daripada identiti masyarakat',w:['Supaya semua kelompok meninggalkan budaya masing-masing','Supaya kegiatan ekonomi dapat dihentikan','Supaya masyarakat tidak berinteraksi dengan kelompok lain']},
{q:'Apakah kesan positif kepelbagaian masyarakat?',a:'Mewujudkan warisan budaya yang kaya dan pelbagai',w:['Menghasilkan hanya satu bentuk kesenian','Menghapuskan perbezaan bahasa dan adat','Menjadikan semua cara hidup seragam']}]},
{title:'Kesenian dan Seni Bina',qs:[
{q:'Antara berikut, manakah paling tepat menggambarkan kesenian tradisional masyarakat Sabah dan Sarawak?',a:'Hasil seni berkait dengan identiti, kemahiran dan sumber persekitaran masyarakat',w:['Hasil seni hanya berfungsi sebagai barang perdagangan','Semua hasil seni mempunyai bentuk yang sama','Kesenian tidak mempunyai hubungan dengan kehidupan masyarakat']},
{q:'I Ukiran. II Anyaman. III Tenunan. IV Fresko Rom. Pilih contoh kesenian tempatan yang tepat.',a:'I, II dan III',w:['I dan IV','II dan IV','III dan IV']},
{q:'Mengapakah rumah panjang dianggap lebih daripada sekadar tempat tinggal?',a:'Mencerminkan kehidupan bersama dan hubungan sosial dalam komuniti',w:['Dibina khusus untuk menyimpan hasil perdagangan luar','Digunakan hanya oleh seorang ketua tanpa keluarga lain','Berfungsi semata-mata sebagai tempat upacara tahunan']},
{q:'Sebuah rumah tradisional menggunakan kayu, buluh dan bahan daripada persekitaran. Apakah nilai yang dapat dirumuskan?',a:'Masyarakat bijak menyesuaikan seni bina dengan sumber dan persekitaran',w:['Masyarakat bergantung sepenuhnya pada bahan import','Seni bina tradisional tidak dipengaruhi alam sekitar','Bahan tempatan hanya digunakan kerana tiada kemahiran membina']},
{q:'Pasangan manakah paling tepat?',a:'Rumah tradisional — mencerminkan cara hidup dan penyesuaian masyarakat',w:['Anyaman — digunakan hanya dalam pentadbiran','Ukiran — tidak mempunyai nilai budaya','Tenunan — berasal sepenuhnya daripada pengaruh moden']}]}];
const sea=document.getElementById('sea'),ship=document.getElementById('ship'),wake=document.getElementById('wake'),pirate=document.getElementById('pirate'),islands=[...document.querySelectorAll('.island')],score=document.getElementById('score'),livesEl=document.getElementById('lives'),quiz=document.getElementById('quiz'),topic=document.getElementById('topic'),missionLabel=document.getElementById('missionLabel'),qCount=document.getElementById('qCount'),bar=document.getElementById('bar'),question=document.getElementById('question'),answers=document.getElementById('answers'),feedback=document.getElementById('feedback'),treasure=document.getElementById('treasure'),sink=document.getElementById('sink'),win=document.getElementById('win'),cannonLayer=document.getElementById('cannonLayer');
let unlocked=0,finished=new Set(),active=-1,qIndex=0,qOrder=[],lives=3,shipX=9,shipY=50,dx=0,dy=0,lastTime=0,nearCooldown=false,audioOn=true,audioStarted=false,audioCtx,oceanNode,oceanGain;
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a}
function updateShip(){ship.style.left=shipX+'%';ship.style.top=shipY+'%';wake.style.left=(shipX-2)+'%';wake.style.top=(shipY+4)+'%';const ang=dx||dy?Math.atan2(dy,dx)*180/Math.PI+90:0;ship.style.transform=`translate(-50%,-50%) rotate(${ang}deg)`}
function refresh(){score.textContent=`${finished.size} / 5`;livesEl.textContent=Array(lives).fill('❤️').join(' ')+Array(3-lives).fill('🖤').join(' ');islands.forEach((b,i)=>{const lock=i>unlocked;b.disabled=lock;b.classList.toggle('locked',lock);b.classList.toggle('open',!lock&&!finished.has(i));b.classList.toggle('done',finished.has(i))});treasure.querySelector('.chest').textContent=finished.size===5?'💰':'🔒'}
function getCenter(el){const s=sea.getBoundingClientRect(),r=el.getBoundingClientRect();return{x:((r.left+r.width/2)-s.left)/s.width*100,y:((r.top+r.height/2)-s.top)/s.height*100}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function checkArrival(){if(quiz.open||sink.open||win.open||nearCooldown)return;const p={x:shipX,y:shipY};for(let i=0;i<islands.length;i++){if(i>unlocked||finished.has(i))continue;const c=getCenter(islands[i]);if(dist(p,c)<8.2){nearCooldown=true;setTimeout(()=>nearCooldown=false,1200);openMission(i);return}}if(finished.size===5){const c=getCenter(treasure);if(dist(p,c)<9){win.showModal();playWinSound()}}}
function step(t){if(!lastTime)lastTime=t;const dt=Math.min(32,t-lastTime);lastTime=t;if(!quiz.open&&!sink.open&&!win.open&&(dx||dy)){const speed=.020*dt;shipX=Math.max(3,Math.min(96,shipX+dx*speed));shipY=Math.max(13,Math.min(91,shipY+dy*speed));updateShip();checkArrival()}requestAnimationFrame(step)}requestAnimationFrame(step);
function bindHold(id,x,y){const b=document.getElementById(id);const start=e=>{e.preventDefault();startAudio();dx=x;dy=y};const stop=e=>{if(e)e.preventDefault();if(dx===x&&dy===y){dx=0;dy=0}};b.addEventListener('pointerdown',start);b.addEventListener('pointerup',stop);b.addEventListener('pointercancel',stop);b.addEventListener('pointerleave',stop)}bindHold('left',-1,0);bindHold('right',1,0);bindHold('up',0,-1);bindHold('down',0,1);
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){startAudio();e.preventDefault();if(e.key==='ArrowLeft'){dx=-1;dy=0}if(e.key==='ArrowRight'){dx=1;dy=0}if(e.key==='ArrowUp'){dx=0;dy=-1}if(e.key==='ArrowDown'){dx=0;dy=1}}});window.addEventListener('keyup',e=>{if(e.key.startsWith('Arrow')){dx=0;dy=0}});
function openMission(i){active=i;qIndex=0;qOrder=shuffle(missions[i].qs);missionLabel.textContent=`MISI ${i+1} DARIPADA 5`;topic.textContent=missions[i].title;renderQuestion();quiz.showModal()}
function renderQuestion(){const item=qOrder[qIndex];qCount.textContent=`Soalan ${qIndex+1} / ${qOrder.length}`;bar.style.width=`${((qIndex+1)/qOrder.length)*100}%`;question.textContent=item.q;feedback.textContent='';feedback.className='';answers.innerHTML='';shuffle([{text:item.a,ok:true},...item.w.map(text=>({text,ok:false}))]).forEach((opt,idx)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<span class="exam-letter">${String.fromCharCode(65+idx)}</span><span>${opt.text}</span>`;b.addEventListener('click',()=>check(opt.ok,b));answers.appendChild(b)})}
function check(ok,button){if(!ok){button.disabled=true;feedback.textContent='💥 Salah! Lanun melepaskan tembakan!';feedback.className='wrong';pirateFire();return}feedback.textContent='✅ Tepat!';feedback.className='correct';qIndex++;if(qIndex<qOrder.length){[...answers.children].forEach(b=>b.disabled=true);setTimeout(renderQuestion,500)}else{finished.add(active);unlocked=Math.max(unlocked,Math.min(4,active+1));refresh();[...answers.children].forEach(b=>b.disabled=true);feedback.textContent=active===4?'🏆 Semua artifak diperoleh. Belayar sendiri ke Harta Warisan!':'🏆 Pulau ditakluki. Belayar ke pulau seterusnya!';setTimeout(()=>quiz.close(),900)}}
function pirateFire(){playCannon();const s=sea.getBoundingClientRect(),pr=pirate.getBoundingClientRect(),sr=ship.getBoundingClientRect();const startX=pr.left+pr.width/2-s.left,startY=pr.top+pr.height/2-s.top,endX=sr.left+sr.width/2-s.left,endY=sr.top+sr.height/2-s.top;const ball=document.createElement('div');ball.className='ball';ball.style.left=startX+'px';ball.style.top=startY+'px';cannonLayer.appendChild(ball);ball.animate([{transform:'translate(0,0)'},{transform:`translate(${endX-startX}px,${endY-startY}px)`}],{duration:520,easing:'ease-in'}).onfinish=()=>{ball.remove();const spl=document.createElement('div');spl.className='splash';spl.textContent='💦';spl.style.left=(endX-18)+'px';spl.style.top=(endY-20)+'px';cannonLayer.appendChild(spl);setTimeout(()=>spl.remove(),700);ship.classList.add('hit');setTimeout(()=>ship.classList.remove('hit'),450);lives--;refresh();if(lives<=0){setTimeout(()=>{if(quiz.open)quiz.close();sink.showModal();},350)}}}
function resetGame(){unlocked=0;finished.clear();lives=3;active=-1;qIndex=0;shipX=9;shipY=50;dx=dy=0;updateShip();if(quiz.open)quiz.close();if(sink.open)sink.close();if(win.open)win.close();refresh()}
document.getElementById('closeQuiz').addEventListener('click',()=>quiz.close());document.getElementById('restart').addEventListener('click',resetGame);document.getElementById('retry').addEventListener('click',resetGame);document.getElementById('playAgain').addEventListener('click',resetGame);
function startAudio(){if(audioStarted||!audioOn)return;audioStarted=true;audioCtx=new (window.AudioContext||window.webkitAudioContext)();const buf=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate);const data=buf.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.55;const src=audioCtx.createBufferSource();src.buffer=buf;src.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;oceanGain=audioCtx.createGain();oceanGain.gain.value=.055;src.connect(filter).connect(oceanGain).connect(audioCtx.destination);src.start();oceanNode=src}
function playCannon(){startAudio();if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(95,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(38,audioCtx.currentTime+.22);g.gain.setValueAtTime(.28,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.3);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.31)}
function playWinSound(){startAudio();if(!audioCtx)return;[523,659,784].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;g.gain.setValueAtTime(.08,audioCtx.currentTime+i*.12);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+i*.12+.3);o.connect(g).connect(audioCtx.destination);o.start(audioCtx.currentTime+i*.12);o.stop(audioCtx.currentTime+i*.12+.31)})}
document.getElementById('soundBtn').addEventListener('click',()=>{audioOn=!audioOn;document.getElementById('soundBtn').textContent=audioOn?'🔊':'🔇';if(audioOn){audioStarted=false;startAudio()}else if(oceanGain)oceanGain.gain.value=0});updateShip();refresh();